<?php

/**
 * @file
 * Contains civimail_digest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function civimail_digest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the civimail_digest module.
    case 'help.page.civimail_digest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send a digest email from new or updated content previously sent by CiviMail.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function civimail_digest_theme() {
  return [
    // @todo set template suggestions
    'civimail_digest_html' => [
      'variables' => [
        'digest_title' => NULL,
        'digest_id' => NULL,
        'entities' => NULL,
        'base_path' => NULL,
        'absolute_link' => NULL,
        'absolute_url' => NULL,
        'translation_links' => NULL,
        'civicrm_header' => NULL,
        'civicrm_footer' => NULL,
        'civicrm_unsubscribe_url' => NULL,
        'is_test' => NULL,
      ],
      'render element' => 'children',
    ],
    'civimail_digest_actions' => [
      'variables' => [
        'configure_url' => NULL,
        'preview_url' => NULL,
        'prepare_url' => NULL,
      ],
    ],
    'civimail_digest_text' => [
      'variables' => [
        'digest_title' => NULL,
        'digest_id' => NULL,
        'entities' => NULL,
        'absolute_url' => NULL,
        'translation_urls' => NULL,
        'civicrm_header' => NULL,
        'civicrm_footer' => NULL,
        'civicrm_unsubscribe_url' => NULL,
        'is_test' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
