<?php

/**
 * @file
 * Contains civimail_digest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function civimail_digest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the civimail_digest module.
    case 'help.page.civimail_digest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send a digest email from new or updated content previously sent by CiviMail.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function civimail_digest_theme() {
  return [
    'civimail_digest' => [
      'render element' => 'children',
    ],
  ];
}
