<?php

/**
 * @file
 * Contains civimail_digest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function civimail_digest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the civimail_digest module.
    case 'help.page.civimail_digest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Send a digest email from new or updated content previously sent by CiviMail.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function civimail_digest_theme() {
  return [
    // @todo set template suggestions
    'civimail_digest_html' => [
      'variables' => [
        'digest_title' => NULL,
        'digest_id' => NULL,
        'entities' => NULL,
        'base_path' => NULL,
        'absolute_link' => NULL,
        'absolute_url' => NULL,
        'translation_links' => NULL,
        'civicrm_header' => NULL,
        'civicrm_footer' => NULL,
        'civicrm_unsubscribe_url' => NULL,
        'is_test' => NULL,
      ],
      'render element' => 'children',
    ],
    'civimail_digest_actions' => [
      'variables' => [
        'configure_url' => NULL,
        'preview_url' => NULL,
        'prepare_url' => NULL,
      ],
    ],
    'civimail_digest_text' => [
      'variables' => [
        'digest_title' => NULL,
        'digest_id' => NULL,
        'entities' => NULL,
        'absolute_url' => NULL,
        'translation_urls' => NULL,
        'civicrm_header' => NULL,
        'civicrm_footer' => NULL,
        'civicrm_unsubscribe_url' => NULL,
        'is_test' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function civimail_digest_cron() {
  /** @var \Drupal\civimail_digest\CiviMailDigestSchedulerInterface $scheduler */
  $scheduler = \Drupal::service('civimail_digest_scheduler');
  if (!$scheduler->executeSchedulerOperation()) {
    \Drupal::logger('civimail_digest')->error(t('CiviMail Digest scheduler failed.'));
  }
}

/**
 * Implements hook_mail().
 */
function civimail_digest_mail($key, &$message, $params) {
  switch ($key) {
    case 'civimail_digest_notify':
      // Customize from mail and name.
      // Override from related headers, leave others to mime mail.
      // @todo check if MimeMail is installed
      $message['headers']['From'] = $params['from_name'] . ' <' . $params['from_mail'] . '>';
      // Currently overridden by default.
      $message['headers']['Sender'] = $params['from_mail'];
      // Currently overridden by default.
      $message['headers']['Return-Path'] = $params['from_mail'];
      // Override Drupal related from keys.
      $message['from'] = $params['from_mail'];
      // Currently overridden by default.
      $message['reply-to'] = $params['from_mail'];

      // Set's the message subject and body as configured.
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}
