<?php

/**
 * @file
 * Contains civimail.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_help().
 */
function civimail_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the civimail module.
    case 'help.page.civimail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integration with CiviCRM CiviMail') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function civimail_theme() {
  return [
    'entity_mailing' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for entity mailing templates.
 *
 * Default template: entity-mailing.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the components of the page
 *     - #entity: The entity that is the subject of the mailing.
 *     - #entity_send_form: A form to send the entity to CiviCRM groups.
 *     - #sent_mailings: The table of already sent mailings for this entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_entity_mailing(array &$variables) {
  $variables['entity'] = $variables['elements']['#entity'];
  $variables['entity_send_form'] = $variables['elements']['#entity_send_form'];
  $variables['sent_mailings'] = $variables['elements']['#sent_mailings'];

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $variables['entity'];
  if ($entity instanceof ContentEntityInterface) {
    $variables['title'] = $variables['entity']->label();
  }

  // @todo add helper variables.
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
